version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DATABASE_URL=$DATABASE_URL
    ports:
      - 3333:3333
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.6
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_PORT:3306
    volumes:
      - ./data/:/var/lib/mysql